// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProjectCalulator
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 12));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(27, 18));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(17, 18));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(23, 18));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(23, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(30, 12));
        }
        
        /// <summary>
        /// MethodPengurangan
        /// </summary>
        public void MethodPengurangan()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(61, 6));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 18));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(23, 14));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(26, 12));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(24, 9));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(30, 14));
        }
        
        /// <summary>
        /// RecordedMethodPengurangan
        /// </summary>
        public void RecordedMethodPengurangan()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(61, 6));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 18));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(23, 14));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(26, 12));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(24, 9));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(30, 14));

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(178, 5));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(35, 10));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(28, 13));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(28, 17));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(26, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(48, 16));
        }
        
        /// <summary>
        /// RecordedMethodPerkalian
        /// </summary>
        public void RecordedMethodPerkalian()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(153, 9));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(25, 23));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(20, 15));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(32, 14));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(30, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(71, 15));
        }
        
        /// <summary>
        /// RecordedMethodPembagian
        /// </summary>
        public void RecordedMethodPembagian()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(156, 12));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(37, 10));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(34, 25));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(32, 14));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(20, 16));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(17, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(34, 12));
        }
        
        #region Properties
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfTitleBar UIMyCalculatorv1TitleBar
        {
            get
            {
                if ((this.mUIMyCalculatorv1TitleBar == null))
                {
                    this.mUIMyCalculatorv1TitleBar = new WpfTitleBar(this);
                    #region Search Criteria
                    this.mUIMyCalculatorv1TitleBar.SearchProperties[WpfTitleBar.PropertyNames.AutomationId] = "TitleBar";
                    this.mUIMyCalculatorv1TitleBar.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIMyCalculatorv1TitleBar;
            }
        }
        
        public WpfButton UIItem7Button
        {
            get
            {
                if ((this.mUIItem7Button == null))
                {
                    this.mUIItem7Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem7Button.SearchProperties[WpfButton.PropertyNames.Name] = "7";
                    this.mUIItem7Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem7Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItemButton1;
        
        private WpfTitleBar mUIMyCalculatorv1TitleBar;
        
        private WpfButton mUIItem7Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItemButton4;
        #endregion
    }
}
